# MSS SD card configuration

set EMMC "EMMC:UNUSED"
set EMMC_DATA_7_4 "EMMC_DATA_7_4:UNUSED"
set EMMC_SD_SDIO_FREQ "EMMC_SD_SDIO_FREQ:200"

set SD "SD:MSSIO_B4"
set SD_CLE "SD_CLE:UNUSED"
set SD_LED "SD_LED:UNUSED"
set SD_LED_IS_INVERTED "SD_LED_IS_INVERTED:false"
set SD_VOLT_0 "SD_VOLT_0:UNUSED"
set SD_VOLT_0_IS_INVERTED "SD_VOLT_0_IS_INVERTED:false"
set SD_VOLT_1 "SD_VOLT_1:UNUSED"
set SD_VOLT_1_IS_INVERTED "SD_VOLT_1_IS_INVERTED:false"
set SD_VOLT_2 "SD_VOLT_2:UNUSED"
set SD_VOLT_2_IS_INVERTED "SD_VOLT_2_IS_INVERTED:false"
set SD_VOLT_CMD_DIR_IS_INVERTED "SD_VOLT_CMD_DIR_IS_INVERTED:true"
set SD_VOLT_DIR_0_IS_INVERTED "SD_VOLT_DIR_0_IS_INVERTED:true"
set SD_VOLT_DIR_1_3_IS_INVERTED "SD_VOLT_DIR_1_3_IS_INVERTED:true"
set SD_VOLT_EN_IS_INVERTED "SD_VOLT_EN_IS_INVERTED:false"
set SD_VOLT_PORTS "SD_VOLT_PORTS:MSSIO_B4"
set SD_VOLT_SEL_IS_INVERTED "SD_VOLT_SEL_IS_INVERTED:true"


