########## This file is automatically generated. Any changes to this file will be lost. ##########
########### If you have your own constraints tcl file, please add it to the project ##########
########### by using the "Set custom config file" constraint in the HLS Constraints dialog. ##########
source $env(LEGUP_ROOT_DIR)/examples/legup.tcl
set_project PolarFireSoC MPFS250T Icicle_SoC

# Include the counter for the profiler
set_parameter SOC_PROFILER_COUNTER 1
