onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -expand -group AXI4_STREAM_DATA_GENERATOR /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/AXI4_STREAM_DATA_GENERATOR_0/PCLK
add wave -noupdate -expand -group AXI4_STREAM_DATA_GENERATOR /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/AXI4_STREAM_DATA_GENERATOR_0/PRESETN
add wave -noupdate -expand -group AXI4_STREAM_DATA_GENERATOR /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/AXI4_STREAM_DATA_GENERATOR_0/PENABLE
add wave -noupdate -expand -group AXI4_STREAM_DATA_GENERATOR /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/AXI4_STREAM_DATA_GENERATOR_0/PSEL
add wave -noupdate -expand -group AXI4_STREAM_DATA_GENERATOR /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/AXI4_STREAM_DATA_GENERATOR_0/PADDR
add wave -noupdate -expand -group AXI4_STREAM_DATA_GENERATOR /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/AXI4_STREAM_DATA_GENERATOR_0/PWRITE
add wave -noupdate -expand -group AXI4_STREAM_DATA_GENERATOR /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/AXI4_STREAM_DATA_GENERATOR_0/PWDATA
add wave -noupdate -expand -group AXI4_STREAM_DATA_GENERATOR /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/AXI4_STREAM_DATA_GENERATOR_0/PRDATA
add wave -noupdate -expand -group AXI4_STREAM_DATA_GENERATOR /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/AXI4_STREAM_DATA_GENERATOR_0/PREADY
add wave -noupdate -expand -group AXI4_STREAM_DATA_GENERATOR /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/AXI4_STREAM_DATA_GENERATOR_0/PSLVERR
add wave -noupdate -expand -group AXI4_STREAM_DATA_GENERATOR /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/AXI4_STREAM_DATA_GENERATOR_0/ACLK
add wave -noupdate -expand -group AXI4_STREAM_DATA_GENERATOR /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/AXI4_STREAM_DATA_GENERATOR_0/RSTN
add wave -noupdate -expand -group AXI4_STREAM_DATA_GENERATOR /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/AXI4_STREAM_DATA_GENERATOR_0/TREADY
add wave -noupdate -expand -group AXI4_STREAM_DATA_GENERATOR /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/AXI4_STREAM_DATA_GENERATOR_0/TDEST
add wave -noupdate -expand -group AXI4_STREAM_DATA_GENERATOR /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/AXI4_STREAM_DATA_GENERATOR_0/TID
add wave -noupdate -expand -group AXI4_STREAM_DATA_GENERATOR /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/AXI4_STREAM_DATA_GENERATOR_0/TKEEP
add wave -noupdate -expand -group AXI4_STREAM_DATA_GENERATOR /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/AXI4_STREAM_DATA_GENERATOR_0/TLAST
add wave -noupdate -expand -group AXI4_STREAM_DATA_GENERATOR /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/AXI4_STREAM_DATA_GENERATOR_0/TVALID
add wave -noupdate -expand -group AXI4_STREAM_DATA_GENERATOR /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/AXI4_STREAM_DATA_GENERATOR_0/TSTRB
add wave -noupdate -expand -group AXI4_STREAM_DATA_GENERATOR /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/AXI4_STREAM_DATA_GENERATOR_0/TDATA
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/CLOCK
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/RESETN
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/TDATA
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/TDEST
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/TID
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/TKEEP
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/INTERRUPT
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/TREADY
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/TLAST
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/TSTRB
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/TVALID
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/DMA_ARREADY
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/DMA_AWREADY
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/DMA_BID
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/DMA_BRESP
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/DMA_BVALID
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/DMA_RDATA
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/DMA_RID
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/DMA_RLAST
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/DMA_RRESP
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/DMA_RVALID
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/DMA_WREADY
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/DMA_ARADDR
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/DMA_ARBURST
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/DMA_ARID
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/DMA_ARLEN
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/DMA_ARSIZE
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/DMA_ARVALID
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/DMA_AWADDR
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/DMA_AWBURST
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/DMA_AWID
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/DMA_AWLEN
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/DMA_AWSIZE
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/DMA_AWVALID
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/DMA_BREADY
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/DMA_RREADY
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/DMA_WDATA
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/DMA_WLAST
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/DMA_WSTRB
add wave -noupdate -expand -group DMA_CONTROLLER /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/DMA_CONTROLLER_inst_0/DMA_WVALID
add wave -noupdate -expand -group SRAM /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/PF_SRAM_AHBL_AXI_C0_0/ACLK
add wave -noupdate -expand -group SRAM /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/PF_SRAM_AHBL_AXI_C0_0/WDATA
add wave -noupdate -expand -group SRAM /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/PF_SRAM_AHBL_AXI_C0_0/WLAST
add wave -noupdate -expand -group SRAM /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/PF_SRAM_AHBL_AXI_C0_0/WSTRB
add wave -noupdate -expand -group SRAM /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/PF_SRAM_AHBL_AXI_C0_0/WVALID
add wave -noupdate -expand -group SRAM /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/PF_SRAM_AHBL_AXI_C0_0/ARADDR
add wave -noupdate -expand -group SRAM /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/PF_SRAM_AHBL_AXI_C0_0/ARBURST
add wave -noupdate -expand -group SRAM /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/PF_SRAM_AHBL_AXI_C0_0/ARCACHE
add wave -noupdate -expand -group SRAM /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/PF_SRAM_AHBL_AXI_C0_0/ARESETN
add wave -noupdate -expand -group SRAM /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/PF_SRAM_AHBL_AXI_C0_0/ARID
add wave -noupdate -expand -group SRAM /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/PF_SRAM_AHBL_AXI_C0_0/ARLEN
add wave -noupdate -expand -group SRAM /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/PF_SRAM_AHBL_AXI_C0_0/ARLOCK
add wave -noupdate -expand -group SRAM /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/PF_SRAM_AHBL_AXI_C0_0/ARPROT
add wave -noupdate -expand -group SRAM /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/PF_SRAM_AHBL_AXI_C0_0/ARSIZE
add wave -noupdate -expand -group SRAM /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/PF_SRAM_AHBL_AXI_C0_0/ARVALID
add wave -noupdate -expand -group SRAM /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/PF_SRAM_AHBL_AXI_C0_0/AWADDR
add wave -noupdate -expand -group SRAM /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/PF_SRAM_AHBL_AXI_C0_0/AWBURST
add wave -noupdate -expand -group SRAM /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/PF_SRAM_AHBL_AXI_C0_0/AWCACHE
add wave -noupdate -expand -group SRAM /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/PF_SRAM_AHBL_AXI_C0_0/AWID
add wave -noupdate -expand -group SRAM /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/PF_SRAM_AHBL_AXI_C0_0/AWLEN
add wave -noupdate -expand -group SRAM /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/PF_SRAM_AHBL_AXI_C0_0/AWLOCK
add wave -noupdate -expand -group SRAM /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/PF_SRAM_AHBL_AXI_C0_0/AWPROT
add wave -noupdate -expand -group SRAM /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/PF_SRAM_AHBL_AXI_C0_0/AWSIZE
add wave -noupdate -expand -group SRAM /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/PF_SRAM_AHBL_AXI_C0_0/AWVALID
add wave -noupdate -expand -group SRAM /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/PF_SRAM_AHBL_AXI_C0_0/BREADY
add wave -noupdate -expand -group SRAM /Test_bench/MPFS_ICICLE_KIT_BASE_DESIGN_0/FIC_0_PERIPHERALS_1/PF_SRAM_AHBL_AXI_C0_0/RREADY

TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {16493562 ps} 0} {{Cursor 2} {382994 ps} 0}
quietly wave cursor active 2
configure wave -namecolwidth 301
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {10500 ns}
